### ISSUE TITLE
AWS returning more items than appearing in Backbone.DynamoDB.Collection

### ISSUE THREAD

**Issue by iancmyers** [serg-io/backbone-dynamodb#4]
I have a collection that is querying DynamoDB. AWS is returning multiple items and the fetchCollection function is calling options.success with multiple items, however the collection that is received in options.success only contains one item. 

**It seems like backbone-dynamodb is expecting the `HashKey` to be unique to each record, which is not necessarily the case.**

Heres's the relevant code:

```js
// collections/entries.js
var Backbone = require('backbone-dynamodb')
  , Entry = require('../models/entry');

var Entries = module.exports = Backbone.DynamoDB.Collection.extend({
  tableName: 'Entries' + process.env.DYNAMODB_TABLE_SUFFIX,
  idAttribute: 'email',
  rangeAttribute: 'createdAt',
  model: Entry
});

// models/entry.js
var Backbone = require('backbone-dynamodb')
  , validator = require('../../lib/validator');

var Entry = module.exports = Backbone.DynamoDB.Model.extend({
  tableName: 'Entries' + process.env.DYNAMODB_TABLE_SUFFIX,
  idAttribute: 'email',
  rangeAttribute: 'createdAt'
});

// routes/entries.js
var Entry = require('../models/entry')
  , Entries = require('../collections/entries')

function index (req, res, next) {
  var entries = new Entries();
  entries.fetch({
    query: { 
      KeyConditions: {
        email: {
          ComparisonOperator: "EQ",
          AttributeValueList: [{ S: req.user.get('email') }]
        }
      },
      Limit: req.params.limit || 25
    },
    success: function (entries) {
      // This JSON only contains 1 item.
      res.json({ entries: entries });
    },
    error: function (entries, err) {
      res.json(404, { message: "Entries not found." })
    }
  });
}
```

Modified backbone-dynamodb code:

```js
function fetchCollection(collection, options) {
	var fetchType = options.query ? 'query' : 'scan',
		body = _.extend({TableName: collection._tableName()}, options[fetchType], options.dynamodb);

	var deferred = new _.Deferred(),
		request = dynamoDB.client[fetchType](body);

	request.on('complete', function(resp) {
		var ctx = options.context || collection;

		if (resp.error) deferred.rejectWith(ctx, [resp, options]);
		else {
			var modelsArray = _.map(resp.data.Items, function(item) {
				var attributes = {};
				_.each(item, function(attribute, key) {
					attributes[key] = decodeAttribute(attribute);
				});
				return attributes;
			});

			options.dynamodbResponse = resp;
			deferred.resolveWith(ctx, [modelsArray, options]);
		}
	});
	request.send();

	wrapComplete(collection, options);
	deferred.done(function () {
        // This will log out multiple items.
		console.log(arguments[0]);
		options.success(arguments[0]);
	}).fail(options.error).always(options.complete);

	return deferred.promise(request);
}
```

**Comment by serg-io** [comment]
I know this issue has been open for over a year and half. Sorry for not looking into it before but I haven't had time to work on this library until very recently.

The problem is a little tricky. Basically `Backbone.Collection` makes the assumption that the models have an unique `id` attribute, so it doesn't allow you to add two or more models with the same id attribute.

I just released version 1.0.0 which includes a work-around for this problem. If a model has a primary range key attribute, use `hashAttribute` instead of `idAttribute`. You can find an example of it [here](https://github.com/serg-io/backbone-dynamodb/blob/master/examples.js#L61). When using `hashAttribute`, is important to keep in mind that `collection.get( id )` would not work as expected. Instead you would have to use something like (using the same model/collection definitions you used in the code you posted):

    var entry = entries.findWhere({ email: 'foo@bar.com', createdAt: dateInstance });

Feel free to create issues if you run into any other problems. I'll try to fix any issues as soon as possible from now on.
