### ISSUE TITLE
Unable to save collection

### ISSUE THREAD

**Issue by ibjhb** [serg-io/backbone-dynamodb#5]
When calling .save() on a collection I get the following error:

TypeError: Object [object Object] has no method 'save'

**Comment by serg-io** [comment]
It's been a while since I had time to work on this library, sorry for not replying earlier.

You're getting that error because a collection doesn't have a `save` method, only models have that method. If you want to save a collection of models all at once, I recommend doing something like:

    collection.each(function(model) {
       model.save();
    });

A shorter alternative would be:

    collection.invoke( 'save' );

By the way, I just release version 1.0.0 that includes a few new features. Make sure to check it out.
